M48
; DRILL file {KiCad (6.0.5)} date Sun Aug 20 19:57:05 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-20T19:57:05-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X67.782Y-48.915
X79.212Y-48.915
X126.837Y-48.915
X138.267Y-48.915
T0
M30
